sonar.projectKey=app-reservas
sonar.projectName=App Reservas
sonar.sources=auth-service,booking-service,notification-service,user-service,frontend
sonar.exclusions=**/node_modules/**,**/coverage/**,**/dist/**,**/build/**,**/.scannerwork/**,**/.next/**,**/*.test.*,**/__tests__/**,**/public/**
sonar.sourceEncoding=UTF-8
sonar.javascript.lcov.reportPaths=coverage/auth-service/lcov.info,coverage/booking-service/lcov.info,coverage/notification-service/lcov.info,coverage/user-service/lcov.info,coverage/frontend/lcov.info
